// source: courier.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf')
var goog = jspb
var global = function () {
  if (this) {
    return this
  }
  if (typeof window !== 'undefined') {
    return window
  }
  if (typeof global !== 'undefined') {
    return global
  }
  if (typeof self !== 'undefined') {
    return self
  }
  return Function('return this')()
}.call(null)

goog.exportSymbol('proto.couriers.v1.AddCourierRequest', null, global)
goog.exportSymbol('proto.couriers.v1.AddCourierResponse', null, global)
goog.exportSymbol('proto.couriers.v1.Capacity', null, global)
goog.exportSymbol('proto.couriers.v1.Courier', null, global)
goog.exportSymbol('proto.couriers.v1.CourierGeo', null, global)
goog.exportSymbol('proto.couriers.v1.DeleteCourierRequest', null, global)
goog.exportSymbol('proto.couriers.v1.DeleteResponse', null, global)
goog.exportSymbol('proto.couriers.v1.GetCourierRequest', null, global)
goog.exportSymbol('proto.couriers.v1.GetCourierResponse', null, global)
goog.exportSymbol('proto.couriers.v1.SearchCouriersRequest', null, global)
goog.exportSymbol('proto.couriers.v1.SearchCouriersResponse', null, global)
goog.exportSymbol('proto.couriers.v1.UpdateCourierRequest', null, global)
goog.exportSymbol('proto.couriers.v1.UpdateCourierResponse', null, global)
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.couriers.v1.Capacity = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.couriers.v1.Capacity, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.couriers.v1.Capacity.displayName = 'proto.couriers.v1.Capacity'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.couriers.v1.Courier = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.couriers.v1.Courier, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.couriers.v1.Courier.displayName = 'proto.couriers.v1.Courier'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.couriers.v1.CourierGeo = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.couriers.v1.CourierGeo, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.couriers.v1.CourierGeo.displayName = 'proto.couriers.v1.CourierGeo'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.couriers.v1.AddCourierRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.couriers.v1.AddCourierRequest, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.couriers.v1.AddCourierRequest.displayName =
    'proto.couriers.v1.AddCourierRequest'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.couriers.v1.AddCourierResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.couriers.v1.AddCourierResponse, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.couriers.v1.AddCourierResponse.displayName =
    'proto.couriers.v1.AddCourierResponse'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.couriers.v1.UpdateCourierRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.couriers.v1.UpdateCourierRequest, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.couriers.v1.UpdateCourierRequest.displayName =
    'proto.couriers.v1.UpdateCourierRequest'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.couriers.v1.UpdateCourierResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.couriers.v1.UpdateCourierResponse, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.couriers.v1.UpdateCourierResponse.displayName =
    'proto.couriers.v1.UpdateCourierResponse'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.couriers.v1.GetCourierRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.couriers.v1.GetCourierRequest, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.couriers.v1.GetCourierRequest.displayName =
    'proto.couriers.v1.GetCourierRequest'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.couriers.v1.GetCourierResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.couriers.v1.GetCourierResponse, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.couriers.v1.GetCourierResponse.displayName =
    'proto.couriers.v1.GetCourierResponse'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.couriers.v1.SearchCouriersRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.couriers.v1.SearchCouriersRequest, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.couriers.v1.SearchCouriersRequest.displayName =
    'proto.couriers.v1.SearchCouriersRequest'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.couriers.v1.SearchCouriersResponse = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.couriers.v1.SearchCouriersResponse.repeatedFields_,
    null
  )
}
goog.inherits(proto.couriers.v1.SearchCouriersResponse, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.couriers.v1.SearchCouriersResponse.displayName =
    'proto.couriers.v1.SearchCouriersResponse'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.couriers.v1.DeleteCourierRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.couriers.v1.DeleteCourierRequest, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.couriers.v1.DeleteCourierRequest.displayName =
    'proto.couriers.v1.DeleteCourierRequest'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.couriers.v1.DeleteResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.couriers.v1.DeleteResponse, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.couriers.v1.DeleteResponse.displayName =
    'proto.couriers.v1.DeleteResponse'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.couriers.v1.Capacity.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.couriers.v1.Capacity.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.couriers.v1.Capacity} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.couriers.v1.Capacity.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        height: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
        width: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
        depth: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.couriers.v1.Capacity}
 */
proto.couriers.v1.Capacity.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.couriers.v1.Capacity()
  return proto.couriers.v1.Capacity.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.couriers.v1.Capacity} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.couriers.v1.Capacity}
 */
proto.couriers.v1.Capacity.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setHeight(value)
        break
      case 2:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setWidth(value)
        break
      case 3:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setDepth(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.couriers.v1.Capacity.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.couriers.v1.Capacity.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.couriers.v1.Capacity} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.couriers.v1.Capacity.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getHeight()
  if (f !== 0.0) {
    writer.writeFloat(1, f)
  }
  f = message.getWidth()
  if (f !== 0.0) {
    writer.writeFloat(2, f)
  }
  f = message.getDepth()
  if (f !== 0.0) {
    writer.writeFloat(3, f)
  }
}

/**
 * optional float height = 1;
 * @return {number}
 */
proto.couriers.v1.Capacity.prototype.getHeight = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.Capacity} returns this
 */
proto.couriers.v1.Capacity.prototype.setHeight = function (value) {
  return jspb.Message.setProto3FloatField(this, 1, value)
}

/**
 * optional float width = 2;
 * @return {number}
 */
proto.couriers.v1.Capacity.prototype.getWidth = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.Capacity} returns this
 */
proto.couriers.v1.Capacity.prototype.setWidth = function (value) {
  return jspb.Message.setProto3FloatField(this, 2, value)
}

/**
 * optional float depth = 3;
 * @return {number}
 */
proto.couriers.v1.Capacity.prototype.getDepth = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.Capacity} returns this
 */
proto.couriers.v1.Capacity.prototype.setDepth = function (value) {
  return jspb.Message.setProto3FloatField(this, 3, value)
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.couriers.v1.Courier.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.couriers.v1.Courier.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.couriers.v1.Courier} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.couriers.v1.Courier.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        id: jspb.Message.getFieldWithDefault(msg, 1, ''),
        name: jspb.Message.getFieldWithDefault(msg, 2, ''),
        org: jspb.Message.getFieldWithDefault(msg, 3, ''),
        longitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
        latitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
        addressid: jspb.Message.getFieldWithDefault(msg, 7, ''),
        capacity:
          (f = msg.getCapacity()) &&
          proto.couriers.v1.Capacity.toObject(includeInstance, f)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.couriers.v1.Courier}
 */
proto.couriers.v1.Courier.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.couriers.v1.Courier()
  return proto.couriers.v1.Courier.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.couriers.v1.Courier} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.couriers.v1.Courier}
 */
proto.couriers.v1.Courier.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString())
        msg.setId(value)
        break
      case 2:
        var value = /** @type {string} */ (reader.readString())
        msg.setName(value)
        break
      case 3:
        var value = /** @type {string} */ (reader.readString())
        msg.setOrg(value)
        break
      case 4:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setLongitude(value)
        break
      case 5:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setLatitude(value)
        break
      case 7:
        var value = /** @type {string} */ (reader.readString())
        msg.setAddressid(value)
        break
      case 8:
        var value = new proto.couriers.v1.Capacity()
        reader.readMessage(
          value,
          proto.couriers.v1.Capacity.deserializeBinaryFromReader
        )
        msg.setCapacity(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.couriers.v1.Courier.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.couriers.v1.Courier.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.couriers.v1.Courier} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.couriers.v1.Courier.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = message.getId()
  if (f.length > 0) {
    writer.writeString(1, f)
  }
  f = message.getName()
  if (f.length > 0) {
    writer.writeString(2, f)
  }
  f = message.getOrg()
  if (f.length > 0) {
    writer.writeString(3, f)
  }
  f = message.getLongitude()
  if (f !== 0.0) {
    writer.writeFloat(4, f)
  }
  f = message.getLatitude()
  if (f !== 0.0) {
    writer.writeFloat(5, f)
  }
  f = message.getAddressid()
  if (f.length > 0) {
    writer.writeString(7, f)
  }
  f = message.getCapacity()
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.couriers.v1.Capacity.serializeBinaryToWriter
    )
  }
}

/**
 * optional string id = 1;
 * @return {string}
 */
proto.couriers.v1.Courier.prototype.getId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.Courier} returns this
 */
proto.couriers.v1.Courier.prototype.setId = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value)
}

/**
 * optional string name = 2;
 * @return {string}
 */
proto.couriers.v1.Courier.prototype.getName = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.Courier} returns this
 */
proto.couriers.v1.Courier.prototype.setName = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value)
}

/**
 * optional string org = 3;
 * @return {string}
 */
proto.couriers.v1.Courier.prototype.getOrg = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.Courier} returns this
 */
proto.couriers.v1.Courier.prototype.setOrg = function (value) {
  return jspb.Message.setProto3StringField(this, 3, value)
}

/**
 * optional float longitude = 4;
 * @return {number}
 */
proto.couriers.v1.Courier.prototype.getLongitude = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.Courier} returns this
 */
proto.couriers.v1.Courier.prototype.setLongitude = function (value) {
  return jspb.Message.setProto3FloatField(this, 4, value)
}

/**
 * optional float latitude = 5;
 * @return {number}
 */
proto.couriers.v1.Courier.prototype.getLatitude = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.Courier} returns this
 */
proto.couriers.v1.Courier.prototype.setLatitude = function (value) {
  return jspb.Message.setProto3FloatField(this, 5, value)
}

/**
 * optional string addressId = 7;
 * @return {string}
 */
proto.couriers.v1.Courier.prototype.getAddressid = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.Courier} returns this
 */
proto.couriers.v1.Courier.prototype.setAddressid = function (value) {
  return jspb.Message.setProto3StringField(this, 7, value)
}

/**
 * optional Capacity capacity = 8;
 * @return {?proto.couriers.v1.Capacity}
 */
proto.couriers.v1.Courier.prototype.getCapacity = function () {
  return /** @type{?proto.couriers.v1.Capacity} */ (
    jspb.Message.getWrapperField(this, proto.couriers.v1.Capacity, 8)
  )
}

/**
 * @param {?proto.couriers.v1.Capacity|undefined} value
 * @return {!proto.couriers.v1.Courier} returns this
 */
proto.couriers.v1.Courier.prototype.setCapacity = function (value) {
  return jspb.Message.setWrapperField(this, 8, value)
}

/**
 * Clears the message field making it undefined.
 * @return {!proto.couriers.v1.Courier} returns this
 */
proto.couriers.v1.Courier.prototype.clearCapacity = function () {
  return this.setCapacity(undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.couriers.v1.Courier.prototype.hasCapacity = function () {
  return jspb.Message.getField(this, 8) != null
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.couriers.v1.CourierGeo.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.couriers.v1.CourierGeo.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.couriers.v1.CourierGeo} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.couriers.v1.CourierGeo.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        courier:
          (f = msg.getCourier()) &&
          proto.couriers.v1.Courier.toObject(includeInstance, f),
        distance: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.couriers.v1.CourierGeo}
 */
proto.couriers.v1.CourierGeo.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.couriers.v1.CourierGeo()
  return proto.couriers.v1.CourierGeo.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.couriers.v1.CourierGeo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.couriers.v1.CourierGeo}
 */
proto.couriers.v1.CourierGeo.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = new proto.couriers.v1.Courier()
        reader.readMessage(
          value,
          proto.couriers.v1.Courier.deserializeBinaryFromReader
        )
        msg.setCourier(value)
        break
      case 2:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setDistance(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.couriers.v1.CourierGeo.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.couriers.v1.CourierGeo.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.couriers.v1.CourierGeo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.couriers.v1.CourierGeo.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getCourier()
  if (f != null) {
    writer.writeMessage(1, f, proto.couriers.v1.Courier.serializeBinaryToWriter)
  }
  f = message.getDistance()
  if (f !== 0.0) {
    writer.writeFloat(2, f)
  }
}

/**
 * optional Courier courier = 1;
 * @return {?proto.couriers.v1.Courier}
 */
proto.couriers.v1.CourierGeo.prototype.getCourier = function () {
  return /** @type{?proto.couriers.v1.Courier} */ (
    jspb.Message.getWrapperField(this, proto.couriers.v1.Courier, 1)
  )
}

/**
 * @param {?proto.couriers.v1.Courier|undefined} value
 * @return {!proto.couriers.v1.CourierGeo} returns this
 */
proto.couriers.v1.CourierGeo.prototype.setCourier = function (value) {
  return jspb.Message.setWrapperField(this, 1, value)
}

/**
 * Clears the message field making it undefined.
 * @return {!proto.couriers.v1.CourierGeo} returns this
 */
proto.couriers.v1.CourierGeo.prototype.clearCourier = function () {
  return this.setCourier(undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.couriers.v1.CourierGeo.prototype.hasCourier = function () {
  return jspb.Message.getField(this, 1) != null
}

/**
 * optional float distance = 2;
 * @return {number}
 */
proto.couriers.v1.CourierGeo.prototype.getDistance = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.CourierGeo} returns this
 */
proto.couriers.v1.CourierGeo.prototype.setDistance = function (value) {
  return jspb.Message.setProto3FloatField(this, 2, value)
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.couriers.v1.AddCourierRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.couriers.v1.AddCourierRequest.toObject(
      opt_includeInstance,
      this
    )
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.couriers.v1.AddCourierRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.couriers.v1.AddCourierRequest.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        requestedby: jspb.Message.getFieldWithDefault(msg, 1, ''),
        org: jspb.Message.getFieldWithDefault(msg, 2, ''),
        name: jspb.Message.getFieldWithDefault(msg, 3, ''),
        postalcode: jspb.Message.getFieldWithDefault(msg, 5, ''),
        country: jspb.Message.getFieldWithDefault(msg, 6, ''),
        longitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
        latitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
        street: jspb.Message.getFieldWithDefault(msg, 9, ''),
        city: jspb.Message.getFieldWithDefault(msg, 10, ''),
        state: jspb.Message.getFieldWithDefault(msg, 11, ''),
        height: jspb.Message.getFloatingPointFieldWithDefault(msg, 12, 0.0),
        width: jspb.Message.getFloatingPointFieldWithDefault(msg, 13, 0.0),
        depth: jspb.Message.getFloatingPointFieldWithDefault(msg, 14, 0.0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.couriers.v1.AddCourierRequest}
 */
proto.couriers.v1.AddCourierRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.couriers.v1.AddCourierRequest()
  return proto.couriers.v1.AddCourierRequest.deserializeBinaryFromReader(
    msg,
    reader
  )
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.couriers.v1.AddCourierRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.couriers.v1.AddCourierRequest}
 */
proto.couriers.v1.AddCourierRequest.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString())
        msg.setRequestedby(value)
        break
      case 2:
        var value = /** @type {string} */ (reader.readString())
        msg.setOrg(value)
        break
      case 3:
        var value = /** @type {string} */ (reader.readString())
        msg.setName(value)
        break
      case 5:
        var value = /** @type {string} */ (reader.readString())
        msg.setPostalcode(value)
        break
      case 6:
        var value = /** @type {string} */ (reader.readString())
        msg.setCountry(value)
        break
      case 7:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setLongitude(value)
        break
      case 8:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setLatitude(value)
        break
      case 9:
        var value = /** @type {string} */ (reader.readString())
        msg.setStreet(value)
        break
      case 10:
        var value = /** @type {string} */ (reader.readString())
        msg.setCity(value)
        break
      case 11:
        var value = /** @type {string} */ (reader.readString())
        msg.setState(value)
        break
      case 12:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setHeight(value)
        break
      case 13:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setWidth(value)
        break
      case 14:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setDepth(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.couriers.v1.AddCourierRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.couriers.v1.AddCourierRequest.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.couriers.v1.AddCourierRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.couriers.v1.AddCourierRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getRequestedby()
  if (f.length > 0) {
    writer.writeString(1, f)
  }
  f = message.getOrg()
  if (f.length > 0) {
    writer.writeString(2, f)
  }
  f = message.getName()
  if (f.length > 0) {
    writer.writeString(3, f)
  }
  f = message.getPostalcode()
  if (f.length > 0) {
    writer.writeString(5, f)
  }
  f = message.getCountry()
  if (f.length > 0) {
    writer.writeString(6, f)
  }
  f = message.getLongitude()
  if (f !== 0.0) {
    writer.writeFloat(7, f)
  }
  f = message.getLatitude()
  if (f !== 0.0) {
    writer.writeFloat(8, f)
  }
  f = message.getStreet()
  if (f.length > 0) {
    writer.writeString(9, f)
  }
  f = message.getCity()
  if (f.length > 0) {
    writer.writeString(10, f)
  }
  f = message.getState()
  if (f.length > 0) {
    writer.writeString(11, f)
  }
  f = message.getHeight()
  if (f !== 0.0) {
    writer.writeFloat(12, f)
  }
  f = message.getWidth()
  if (f !== 0.0) {
    writer.writeFloat(13, f)
  }
  f = message.getDepth()
  if (f !== 0.0) {
    writer.writeFloat(14, f)
  }
}

/**
 * optional string requestedBy = 1;
 * @return {string}
 */
proto.couriers.v1.AddCourierRequest.prototype.getRequestedby = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.AddCourierRequest} returns this
 */
proto.couriers.v1.AddCourierRequest.prototype.setRequestedby = function (
  value
) {
  return jspb.Message.setProto3StringField(this, 1, value)
}

/**
 * optional string org = 2;
 * @return {string}
 */
proto.couriers.v1.AddCourierRequest.prototype.getOrg = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.AddCourierRequest} returns this
 */
proto.couriers.v1.AddCourierRequest.prototype.setOrg = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value)
}

/**
 * optional string name = 3;
 * @return {string}
 */
proto.couriers.v1.AddCourierRequest.prototype.getName = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.AddCourierRequest} returns this
 */
proto.couriers.v1.AddCourierRequest.prototype.setName = function (value) {
  return jspb.Message.setProto3StringField(this, 3, value)
}

/**
 * optional string postalCode = 5;
 * @return {string}
 */
proto.couriers.v1.AddCourierRequest.prototype.getPostalcode = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.AddCourierRequest} returns this
 */
proto.couriers.v1.AddCourierRequest.prototype.setPostalcode = function (value) {
  return jspb.Message.setProto3StringField(this, 5, value)
}

/**
 * optional string country = 6;
 * @return {string}
 */
proto.couriers.v1.AddCourierRequest.prototype.getCountry = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.AddCourierRequest} returns this
 */
proto.couriers.v1.AddCourierRequest.prototype.setCountry = function (value) {
  return jspb.Message.setProto3StringField(this, 6, value)
}

/**
 * optional float longitude = 7;
 * @return {number}
 */
proto.couriers.v1.AddCourierRequest.prototype.getLongitude = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.AddCourierRequest} returns this
 */
proto.couriers.v1.AddCourierRequest.prototype.setLongitude = function (value) {
  return jspb.Message.setProto3FloatField(this, 7, value)
}

/**
 * optional float latitude = 8;
 * @return {number}
 */
proto.couriers.v1.AddCourierRequest.prototype.getLatitude = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.AddCourierRequest} returns this
 */
proto.couriers.v1.AddCourierRequest.prototype.setLatitude = function (value) {
  return jspb.Message.setProto3FloatField(this, 8, value)
}

/**
 * optional string street = 9;
 * @return {string}
 */
proto.couriers.v1.AddCourierRequest.prototype.getStreet = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.AddCourierRequest} returns this
 */
proto.couriers.v1.AddCourierRequest.prototype.setStreet = function (value) {
  return jspb.Message.setProto3StringField(this, 9, value)
}

/**
 * optional string city = 10;
 * @return {string}
 */
proto.couriers.v1.AddCourierRequest.prototype.getCity = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.AddCourierRequest} returns this
 */
proto.couriers.v1.AddCourierRequest.prototype.setCity = function (value) {
  return jspb.Message.setProto3StringField(this, 10, value)
}

/**
 * optional string state = 11;
 * @return {string}
 */
proto.couriers.v1.AddCourierRequest.prototype.getState = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.AddCourierRequest} returns this
 */
proto.couriers.v1.AddCourierRequest.prototype.setState = function (value) {
  return jspb.Message.setProto3StringField(this, 11, value)
}

/**
 * optional float height = 12;
 * @return {number}
 */
proto.couriers.v1.AddCourierRequest.prototype.getHeight = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 12, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.AddCourierRequest} returns this
 */
proto.couriers.v1.AddCourierRequest.prototype.setHeight = function (value) {
  return jspb.Message.setProto3FloatField(this, 12, value)
}

/**
 * optional float width = 13;
 * @return {number}
 */
proto.couriers.v1.AddCourierRequest.prototype.getWidth = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 13, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.AddCourierRequest} returns this
 */
proto.couriers.v1.AddCourierRequest.prototype.setWidth = function (value) {
  return jspb.Message.setProto3FloatField(this, 13, value)
}

/**
 * optional float depth = 14;
 * @return {number}
 */
proto.couriers.v1.AddCourierRequest.prototype.getDepth = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 14, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.AddCourierRequest} returns this
 */
proto.couriers.v1.AddCourierRequest.prototype.setDepth = function (value) {
  return jspb.Message.setProto3FloatField(this, 14, value)
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.couriers.v1.AddCourierResponse.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.couriers.v1.AddCourierResponse.toObject(
      opt_includeInstance,
      this
    )
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.couriers.v1.AddCourierResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.couriers.v1.AddCourierResponse.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        ok: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
        courier:
          (f = msg.getCourier()) &&
          proto.couriers.v1.Courier.toObject(includeInstance, f)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.couriers.v1.AddCourierResponse}
 */
proto.couriers.v1.AddCourierResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.couriers.v1.AddCourierResponse()
  return proto.couriers.v1.AddCourierResponse.deserializeBinaryFromReader(
    msg,
    reader
  )
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.couriers.v1.AddCourierResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.couriers.v1.AddCourierResponse}
 */
proto.couriers.v1.AddCourierResponse.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {boolean} */ (reader.readBool())
        msg.setOk(value)
        break
      case 2:
        var value = new proto.couriers.v1.Courier()
        reader.readMessage(
          value,
          proto.couriers.v1.Courier.deserializeBinaryFromReader
        )
        msg.setCourier(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.couriers.v1.AddCourierResponse.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.couriers.v1.AddCourierResponse.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.couriers.v1.AddCourierResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.couriers.v1.AddCourierResponse.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getOk()
  if (f) {
    writer.writeBool(1, f)
  }
  f = message.getCourier()
  if (f != null) {
    writer.writeMessage(2, f, proto.couriers.v1.Courier.serializeBinaryToWriter)
  }
}

/**
 * optional bool ok = 1;
 * @return {boolean}
 */
proto.couriers.v1.AddCourierResponse.prototype.getOk = function () {
  return /** @type {boolean} */ (
    jspb.Message.getBooleanFieldWithDefault(this, 1, false)
  )
}

/**
 * @param {boolean} value
 * @return {!proto.couriers.v1.AddCourierResponse} returns this
 */
proto.couriers.v1.AddCourierResponse.prototype.setOk = function (value) {
  return jspb.Message.setProto3BooleanField(this, 1, value)
}

/**
 * optional Courier courier = 2;
 * @return {?proto.couriers.v1.Courier}
 */
proto.couriers.v1.AddCourierResponse.prototype.getCourier = function () {
  return /** @type{?proto.couriers.v1.Courier} */ (
    jspb.Message.getWrapperField(this, proto.couriers.v1.Courier, 2)
  )
}

/**
 * @param {?proto.couriers.v1.Courier|undefined} value
 * @return {!proto.couriers.v1.AddCourierResponse} returns this
 */
proto.couriers.v1.AddCourierResponse.prototype.setCourier = function (value) {
  return jspb.Message.setWrapperField(this, 2, value)
}

/**
 * Clears the message field making it undefined.
 * @return {!proto.couriers.v1.AddCourierResponse} returns this
 */
proto.couriers.v1.AddCourierResponse.prototype.clearCourier = function () {
  return this.setCourier(undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.couriers.v1.AddCourierResponse.prototype.hasCourier = function () {
  return jspb.Message.getField(this, 2) != null
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.couriers.v1.UpdateCourierRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.couriers.v1.UpdateCourierRequest.toObject(
      opt_includeInstance,
      this
    )
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.couriers.v1.UpdateCourierRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.couriers.v1.UpdateCourierRequest.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        id: jspb.Message.getFieldWithDefault(msg, 1, ''),
        requestedby: jspb.Message.getFieldWithDefault(msg, 2, ''),
        postalcode: jspb.Message.getFieldWithDefault(msg, 3, ''),
        country: jspb.Message.getFieldWithDefault(msg, 4, ''),
        longitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
        latitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
        street: jspb.Message.getFieldWithDefault(msg, 7, ''),
        city: jspb.Message.getFieldWithDefault(msg, 8, ''),
        state: jspb.Message.getFieldWithDefault(msg, 9, ''),
        height: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0),
        width: jspb.Message.getFloatingPointFieldWithDefault(msg, 11, 0.0),
        depth: jspb.Message.getFloatingPointFieldWithDefault(msg, 12, 0.0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.couriers.v1.UpdateCourierRequest}
 */
proto.couriers.v1.UpdateCourierRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.couriers.v1.UpdateCourierRequest()
  return proto.couriers.v1.UpdateCourierRequest.deserializeBinaryFromReader(
    msg,
    reader
  )
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.couriers.v1.UpdateCourierRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.couriers.v1.UpdateCourierRequest}
 */
proto.couriers.v1.UpdateCourierRequest.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString())
        msg.setId(value)
        break
      case 2:
        var value = /** @type {string} */ (reader.readString())
        msg.setRequestedby(value)
        break
      case 3:
        var value = /** @type {string} */ (reader.readString())
        msg.setPostalcode(value)
        break
      case 4:
        var value = /** @type {string} */ (reader.readString())
        msg.setCountry(value)
        break
      case 5:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setLongitude(value)
        break
      case 6:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setLatitude(value)
        break
      case 7:
        var value = /** @type {string} */ (reader.readString())
        msg.setStreet(value)
        break
      case 8:
        var value = /** @type {string} */ (reader.readString())
        msg.setCity(value)
        break
      case 9:
        var value = /** @type {string} */ (reader.readString())
        msg.setState(value)
        break
      case 10:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setHeight(value)
        break
      case 11:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setWidth(value)
        break
      case 12:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setDepth(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.couriers.v1.UpdateCourierRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.couriers.v1.UpdateCourierRequest.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.couriers.v1.UpdateCourierRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.couriers.v1.UpdateCourierRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getId()
  if (f.length > 0) {
    writer.writeString(1, f)
  }
  f = message.getRequestedby()
  if (f.length > 0) {
    writer.writeString(2, f)
  }
  f = message.getPostalcode()
  if (f.length > 0) {
    writer.writeString(3, f)
  }
  f = message.getCountry()
  if (f.length > 0) {
    writer.writeString(4, f)
  }
  f = message.getLongitude()
  if (f !== 0.0) {
    writer.writeFloat(5, f)
  }
  f = message.getLatitude()
  if (f !== 0.0) {
    writer.writeFloat(6, f)
  }
  f = message.getStreet()
  if (f.length > 0) {
    writer.writeString(7, f)
  }
  f = message.getCity()
  if (f.length > 0) {
    writer.writeString(8, f)
  }
  f = message.getState()
  if (f.length > 0) {
    writer.writeString(9, f)
  }
  f = message.getHeight()
  if (f !== 0.0) {
    writer.writeFloat(10, f)
  }
  f = message.getWidth()
  if (f !== 0.0) {
    writer.writeFloat(11, f)
  }
  f = message.getDepth()
  if (f !== 0.0) {
    writer.writeFloat(12, f)
  }
}

/**
 * optional string id = 1;
 * @return {string}
 */
proto.couriers.v1.UpdateCourierRequest.prototype.getId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.UpdateCourierRequest} returns this
 */
proto.couriers.v1.UpdateCourierRequest.prototype.setId = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value)
}

/**
 * optional string requestedBy = 2;
 * @return {string}
 */
proto.couriers.v1.UpdateCourierRequest.prototype.getRequestedby = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.UpdateCourierRequest} returns this
 */
proto.couriers.v1.UpdateCourierRequest.prototype.setRequestedby = function (
  value
) {
  return jspb.Message.setProto3StringField(this, 2, value)
}

/**
 * optional string postalCode = 3;
 * @return {string}
 */
proto.couriers.v1.UpdateCourierRequest.prototype.getPostalcode = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.UpdateCourierRequest} returns this
 */
proto.couriers.v1.UpdateCourierRequest.prototype.setPostalcode = function (
  value
) {
  return jspb.Message.setProto3StringField(this, 3, value)
}

/**
 * optional string country = 4;
 * @return {string}
 */
proto.couriers.v1.UpdateCourierRequest.prototype.getCountry = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.UpdateCourierRequest} returns this
 */
proto.couriers.v1.UpdateCourierRequest.prototype.setCountry = function (value) {
  return jspb.Message.setProto3StringField(this, 4, value)
}

/**
 * optional float longitude = 5;
 * @return {number}
 */
proto.couriers.v1.UpdateCourierRequest.prototype.getLongitude = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.UpdateCourierRequest} returns this
 */
proto.couriers.v1.UpdateCourierRequest.prototype.setLongitude = function (
  value
) {
  return jspb.Message.setProto3FloatField(this, 5, value)
}

/**
 * optional float latitude = 6;
 * @return {number}
 */
proto.couriers.v1.UpdateCourierRequest.prototype.getLatitude = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.UpdateCourierRequest} returns this
 */
proto.couriers.v1.UpdateCourierRequest.prototype.setLatitude = function (
  value
) {
  return jspb.Message.setProto3FloatField(this, 6, value)
}

/**
 * optional string street = 7;
 * @return {string}
 */
proto.couriers.v1.UpdateCourierRequest.prototype.getStreet = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.UpdateCourierRequest} returns this
 */
proto.couriers.v1.UpdateCourierRequest.prototype.setStreet = function (value) {
  return jspb.Message.setProto3StringField(this, 7, value)
}

/**
 * optional string city = 8;
 * @return {string}
 */
proto.couriers.v1.UpdateCourierRequest.prototype.getCity = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.UpdateCourierRequest} returns this
 */
proto.couriers.v1.UpdateCourierRequest.prototype.setCity = function (value) {
  return jspb.Message.setProto3StringField(this, 8, value)
}

/**
 * optional string state = 9;
 * @return {string}
 */
proto.couriers.v1.UpdateCourierRequest.prototype.getState = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.UpdateCourierRequest} returns this
 */
proto.couriers.v1.UpdateCourierRequest.prototype.setState = function (value) {
  return jspb.Message.setProto3StringField(this, 9, value)
}

/**
 * optional float height = 10;
 * @return {number}
 */
proto.couriers.v1.UpdateCourierRequest.prototype.getHeight = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.UpdateCourierRequest} returns this
 */
proto.couriers.v1.UpdateCourierRequest.prototype.setHeight = function (value) {
  return jspb.Message.setProto3FloatField(this, 10, value)
}

/**
 * optional float width = 11;
 * @return {number}
 */
proto.couriers.v1.UpdateCourierRequest.prototype.getWidth = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 11, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.UpdateCourierRequest} returns this
 */
proto.couriers.v1.UpdateCourierRequest.prototype.setWidth = function (value) {
  return jspb.Message.setProto3FloatField(this, 11, value)
}

/**
 * optional float depth = 12;
 * @return {number}
 */
proto.couriers.v1.UpdateCourierRequest.prototype.getDepth = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 12, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.UpdateCourierRequest} returns this
 */
proto.couriers.v1.UpdateCourierRequest.prototype.setDepth = function (value) {
  return jspb.Message.setProto3FloatField(this, 12, value)
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.couriers.v1.UpdateCourierResponse.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.couriers.v1.UpdateCourierResponse.toObject(
      opt_includeInstance,
      this
    )
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.couriers.v1.UpdateCourierResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.couriers.v1.UpdateCourierResponse.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        ok: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
        courier:
          (f = msg.getCourier()) &&
          proto.couriers.v1.Courier.toObject(includeInstance, f)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.couriers.v1.UpdateCourierResponse}
 */
proto.couriers.v1.UpdateCourierResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.couriers.v1.UpdateCourierResponse()
  return proto.couriers.v1.UpdateCourierResponse.deserializeBinaryFromReader(
    msg,
    reader
  )
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.couriers.v1.UpdateCourierResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.couriers.v1.UpdateCourierResponse}
 */
proto.couriers.v1.UpdateCourierResponse.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {boolean} */ (reader.readBool())
        msg.setOk(value)
        break
      case 2:
        var value = new proto.couriers.v1.Courier()
        reader.readMessage(
          value,
          proto.couriers.v1.Courier.deserializeBinaryFromReader
        )
        msg.setCourier(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.couriers.v1.UpdateCourierResponse.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter()
    proto.couriers.v1.UpdateCourierResponse.serializeBinaryToWriter(
      this,
      writer
    )
    return writer.getResultBuffer()
  }

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.couriers.v1.UpdateCourierResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.couriers.v1.UpdateCourierResponse.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getOk()
  if (f) {
    writer.writeBool(1, f)
  }
  f = message.getCourier()
  if (f != null) {
    writer.writeMessage(2, f, proto.couriers.v1.Courier.serializeBinaryToWriter)
  }
}

/**
 * optional bool ok = 1;
 * @return {boolean}
 */
proto.couriers.v1.UpdateCourierResponse.prototype.getOk = function () {
  return /** @type {boolean} */ (
    jspb.Message.getBooleanFieldWithDefault(this, 1, false)
  )
}

/**
 * @param {boolean} value
 * @return {!proto.couriers.v1.UpdateCourierResponse} returns this
 */
proto.couriers.v1.UpdateCourierResponse.prototype.setOk = function (value) {
  return jspb.Message.setProto3BooleanField(this, 1, value)
}

/**
 * optional Courier courier = 2;
 * @return {?proto.couriers.v1.Courier}
 */
proto.couriers.v1.UpdateCourierResponse.prototype.getCourier = function () {
  return /** @type{?proto.couriers.v1.Courier} */ (
    jspb.Message.getWrapperField(this, proto.couriers.v1.Courier, 2)
  )
}

/**
 * @param {?proto.couriers.v1.Courier|undefined} value
 * @return {!proto.couriers.v1.UpdateCourierResponse} returns this
 */
proto.couriers.v1.UpdateCourierResponse.prototype.setCourier = function (
  value
) {
  return jspb.Message.setWrapperField(this, 2, value)
}

/**
 * Clears the message field making it undefined.
 * @return {!proto.couriers.v1.UpdateCourierResponse} returns this
 */
proto.couriers.v1.UpdateCourierResponse.prototype.clearCourier = function () {
  return this.setCourier(undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.couriers.v1.UpdateCourierResponse.prototype.hasCourier = function () {
  return jspb.Message.getField(this, 2) != null
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.couriers.v1.GetCourierRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.couriers.v1.GetCourierRequest.toObject(
      opt_includeInstance,
      this
    )
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.couriers.v1.GetCourierRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.couriers.v1.GetCourierRequest.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        id: jspb.Message.getFieldWithDefault(msg, 1, '')
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.couriers.v1.GetCourierRequest}
 */
proto.couriers.v1.GetCourierRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.couriers.v1.GetCourierRequest()
  return proto.couriers.v1.GetCourierRequest.deserializeBinaryFromReader(
    msg,
    reader
  )
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.couriers.v1.GetCourierRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.couriers.v1.GetCourierRequest}
 */
proto.couriers.v1.GetCourierRequest.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString())
        msg.setId(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.couriers.v1.GetCourierRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.couriers.v1.GetCourierRequest.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.couriers.v1.GetCourierRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.couriers.v1.GetCourierRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getId()
  if (f.length > 0) {
    writer.writeString(1, f)
  }
}

/**
 * optional string id = 1;
 * @return {string}
 */
proto.couriers.v1.GetCourierRequest.prototype.getId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.GetCourierRequest} returns this
 */
proto.couriers.v1.GetCourierRequest.prototype.setId = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value)
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.couriers.v1.GetCourierResponse.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.couriers.v1.GetCourierResponse.toObject(
      opt_includeInstance,
      this
    )
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.couriers.v1.GetCourierResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.couriers.v1.GetCourierResponse.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        courier:
          (f = msg.getCourier()) &&
          proto.couriers.v1.Courier.toObject(includeInstance, f)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.couriers.v1.GetCourierResponse}
 */
proto.couriers.v1.GetCourierResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.couriers.v1.GetCourierResponse()
  return proto.couriers.v1.GetCourierResponse.deserializeBinaryFromReader(
    msg,
    reader
  )
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.couriers.v1.GetCourierResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.couriers.v1.GetCourierResponse}
 */
proto.couriers.v1.GetCourierResponse.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = new proto.couriers.v1.Courier()
        reader.readMessage(
          value,
          proto.couriers.v1.Courier.deserializeBinaryFromReader
        )
        msg.setCourier(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.couriers.v1.GetCourierResponse.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.couriers.v1.GetCourierResponse.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.couriers.v1.GetCourierResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.couriers.v1.GetCourierResponse.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getCourier()
  if (f != null) {
    writer.writeMessage(1, f, proto.couriers.v1.Courier.serializeBinaryToWriter)
  }
}

/**
 * optional Courier courier = 1;
 * @return {?proto.couriers.v1.Courier}
 */
proto.couriers.v1.GetCourierResponse.prototype.getCourier = function () {
  return /** @type{?proto.couriers.v1.Courier} */ (
    jspb.Message.getWrapperField(this, proto.couriers.v1.Courier, 1)
  )
}

/**
 * @param {?proto.couriers.v1.Courier|undefined} value
 * @return {!proto.couriers.v1.GetCourierResponse} returns this
 */
proto.couriers.v1.GetCourierResponse.prototype.setCourier = function (value) {
  return jspb.Message.setWrapperField(this, 1, value)
}

/**
 * Clears the message field making it undefined.
 * @return {!proto.couriers.v1.GetCourierResponse} returns this
 */
proto.couriers.v1.GetCourierResponse.prototype.clearCourier = function () {
  return this.setCourier(undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.couriers.v1.GetCourierResponse.prototype.hasCourier = function () {
  return jspb.Message.getField(this, 1) != null
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.couriers.v1.SearchCouriersRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.couriers.v1.SearchCouriersRequest.toObject(
      opt_includeInstance,
      this
    )
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.couriers.v1.SearchCouriersRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.couriers.v1.SearchCouriersRequest.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        org: jspb.Message.getFieldWithDefault(msg, 1, ''),
        postalcode: jspb.Message.getFieldWithDefault(msg, 2, ''),
        country: jspb.Message.getFieldWithDefault(msg, 3, ''),
        longitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
        latitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
        distance: jspb.Message.getFieldWithDefault(msg, 6, 0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.couriers.v1.SearchCouriersRequest}
 */
proto.couriers.v1.SearchCouriersRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.couriers.v1.SearchCouriersRequest()
  return proto.couriers.v1.SearchCouriersRequest.deserializeBinaryFromReader(
    msg,
    reader
  )
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.couriers.v1.SearchCouriersRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.couriers.v1.SearchCouriersRequest}
 */
proto.couriers.v1.SearchCouriersRequest.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString())
        msg.setOrg(value)
        break
      case 2:
        var value = /** @type {string} */ (reader.readString())
        msg.setPostalcode(value)
        break
      case 3:
        var value = /** @type {string} */ (reader.readString())
        msg.setCountry(value)
        break
      case 4:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setLongitude(value)
        break
      case 5:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setLatitude(value)
        break
      case 6:
        var value = /** @type {number} */ (reader.readUint32())
        msg.setDistance(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.couriers.v1.SearchCouriersRequest.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter()
    proto.couriers.v1.SearchCouriersRequest.serializeBinaryToWriter(
      this,
      writer
    )
    return writer.getResultBuffer()
  }

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.couriers.v1.SearchCouriersRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.couriers.v1.SearchCouriersRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getOrg()
  if (f.length > 0) {
    writer.writeString(1, f)
  }
  f = message.getPostalcode()
  if (f.length > 0) {
    writer.writeString(2, f)
  }
  f = message.getCountry()
  if (f.length > 0) {
    writer.writeString(3, f)
  }
  f = message.getLongitude()
  if (f !== 0.0) {
    writer.writeFloat(4, f)
  }
  f = message.getLatitude()
  if (f !== 0.0) {
    writer.writeFloat(5, f)
  }
  f = message.getDistance()
  if (f !== 0) {
    writer.writeUint32(6, f)
  }
}

/**
 * optional string org = 1;
 * @return {string}
 */
proto.couriers.v1.SearchCouriersRequest.prototype.getOrg = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.SearchCouriersRequest} returns this
 */
proto.couriers.v1.SearchCouriersRequest.prototype.setOrg = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value)
}

/**
 * optional string postalCode = 2;
 * @return {string}
 */
proto.couriers.v1.SearchCouriersRequest.prototype.getPostalcode = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.SearchCouriersRequest} returns this
 */
proto.couriers.v1.SearchCouriersRequest.prototype.setPostalcode = function (
  value
) {
  return jspb.Message.setProto3StringField(this, 2, value)
}

/**
 * optional string country = 3;
 * @return {string}
 */
proto.couriers.v1.SearchCouriersRequest.prototype.getCountry = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.SearchCouriersRequest} returns this
 */
proto.couriers.v1.SearchCouriersRequest.prototype.setCountry = function (
  value
) {
  return jspb.Message.setProto3StringField(this, 3, value)
}

/**
 * optional float longitude = 4;
 * @return {number}
 */
proto.couriers.v1.SearchCouriersRequest.prototype.getLongitude = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.SearchCouriersRequest} returns this
 */
proto.couriers.v1.SearchCouriersRequest.prototype.setLongitude = function (
  value
) {
  return jspb.Message.setProto3FloatField(this, 4, value)
}

/**
 * optional float latitude = 5;
 * @return {number}
 */
proto.couriers.v1.SearchCouriersRequest.prototype.getLatitude = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.SearchCouriersRequest} returns this
 */
proto.couriers.v1.SearchCouriersRequest.prototype.setLatitude = function (
  value
) {
  return jspb.Message.setProto3FloatField(this, 5, value)
}

/**
 * optional uint32 distance = 6;
 * @return {number}
 */
proto.couriers.v1.SearchCouriersRequest.prototype.getDistance = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0))
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.SearchCouriersRequest} returns this
 */
proto.couriers.v1.SearchCouriersRequest.prototype.setDistance = function (
  value
) {
  return jspb.Message.setProto3IntField(this, 6, value)
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.couriers.v1.SearchCouriersResponse.repeatedFields_ = [1]

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.couriers.v1.SearchCouriersResponse.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.couriers.v1.SearchCouriersResponse.toObject(
      opt_includeInstance,
      this
    )
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.couriers.v1.SearchCouriersResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.couriers.v1.SearchCouriersResponse.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        couriersList: jspb.Message.toObjectList(
          msg.getCouriersList(),
          proto.couriers.v1.CourierGeo.toObject,
          includeInstance
        ),
        longitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
        latitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.couriers.v1.SearchCouriersResponse}
 */
proto.couriers.v1.SearchCouriersResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.couriers.v1.SearchCouriersResponse()
  return proto.couriers.v1.SearchCouriersResponse.deserializeBinaryFromReader(
    msg,
    reader
  )
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.couriers.v1.SearchCouriersResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.couriers.v1.SearchCouriersResponse}
 */
proto.couriers.v1.SearchCouriersResponse.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break
      }
      var field = reader.getFieldNumber()
      switch (field) {
        case 1:
          var value = new proto.couriers.v1.CourierGeo()
          reader.readMessage(
            value,
            proto.couriers.v1.CourierGeo.deserializeBinaryFromReader
          )
          msg.addCouriers(value)
          break
        case 2:
          var value = /** @type {number} */ (reader.readFloat())
          msg.setLongitude(value)
          break
        case 3:
          var value = /** @type {number} */ (reader.readFloat())
          msg.setLatitude(value)
          break
        default:
          reader.skipField()
          break
      }
    }
    return msg
  }

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.couriers.v1.SearchCouriersResponse.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter()
    proto.couriers.v1.SearchCouriersResponse.serializeBinaryToWriter(
      this,
      writer
    )
    return writer.getResultBuffer()
  }

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.couriers.v1.SearchCouriersResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.couriers.v1.SearchCouriersResponse.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getCouriersList()
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.couriers.v1.CourierGeo.serializeBinaryToWriter
    )
  }
  f = message.getLongitude()
  if (f !== 0.0) {
    writer.writeFloat(2, f)
  }
  f = message.getLatitude()
  if (f !== 0.0) {
    writer.writeFloat(3, f)
  }
}

/**
 * repeated CourierGeo couriers = 1;
 * @return {!Array<!proto.couriers.v1.CourierGeo>}
 */
proto.couriers.v1.SearchCouriersResponse.prototype.getCouriersList =
  function () {
    return /** @type{!Array<!proto.couriers.v1.CourierGeo>} */ (
      jspb.Message.getRepeatedWrapperField(
        this,
        proto.couriers.v1.CourierGeo,
        1
      )
    )
  }

/**
 * @param {!Array<!proto.couriers.v1.CourierGeo>} value
 * @return {!proto.couriers.v1.SearchCouriersResponse} returns this
 */
proto.couriers.v1.SearchCouriersResponse.prototype.setCouriersList = function (
  value
) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value)
}

/**
 * @param {!proto.couriers.v1.CourierGeo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.couriers.v1.CourierGeo}
 */
proto.couriers.v1.SearchCouriersResponse.prototype.addCouriers = function (
  opt_value,
  opt_index
) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    1,
    opt_value,
    proto.couriers.v1.CourierGeo,
    opt_index
  )
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.couriers.v1.SearchCouriersResponse} returns this
 */
proto.couriers.v1.SearchCouriersResponse.prototype.clearCouriersList =
  function () {
    return this.setCouriersList([])
  }

/**
 * optional float longitude = 2;
 * @return {number}
 */
proto.couriers.v1.SearchCouriersResponse.prototype.getLongitude = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.SearchCouriersResponse} returns this
 */
proto.couriers.v1.SearchCouriersResponse.prototype.setLongitude = function (
  value
) {
  return jspb.Message.setProto3FloatField(this, 2, value)
}

/**
 * optional float latitude = 3;
 * @return {number}
 */
proto.couriers.v1.SearchCouriersResponse.prototype.getLatitude = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.couriers.v1.SearchCouriersResponse} returns this
 */
proto.couriers.v1.SearchCouriersResponse.prototype.setLatitude = function (
  value
) {
  return jspb.Message.setProto3FloatField(this, 3, value)
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.couriers.v1.DeleteCourierRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.couriers.v1.DeleteCourierRequest.toObject(
      opt_includeInstance,
      this
    )
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.couriers.v1.DeleteCourierRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.couriers.v1.DeleteCourierRequest.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        id: jspb.Message.getFieldWithDefault(msg, 1, '')
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.couriers.v1.DeleteCourierRequest}
 */
proto.couriers.v1.DeleteCourierRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.couriers.v1.DeleteCourierRequest()
  return proto.couriers.v1.DeleteCourierRequest.deserializeBinaryFromReader(
    msg,
    reader
  )
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.couriers.v1.DeleteCourierRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.couriers.v1.DeleteCourierRequest}
 */
proto.couriers.v1.DeleteCourierRequest.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString())
        msg.setId(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.couriers.v1.DeleteCourierRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.couriers.v1.DeleteCourierRequest.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.couriers.v1.DeleteCourierRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.couriers.v1.DeleteCourierRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getId()
  if (f.length > 0) {
    writer.writeString(1, f)
  }
}

/**
 * optional string id = 1;
 * @return {string}
 */
proto.couriers.v1.DeleteCourierRequest.prototype.getId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''))
}

/**
 * @param {string} value
 * @return {!proto.couriers.v1.DeleteCourierRequest} returns this
 */
proto.couriers.v1.DeleteCourierRequest.prototype.setId = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value)
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.couriers.v1.DeleteResponse.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.couriers.v1.DeleteResponse.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.couriers.v1.DeleteResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.couriers.v1.DeleteResponse.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        ok: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.couriers.v1.DeleteResponse}
 */
proto.couriers.v1.DeleteResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.couriers.v1.DeleteResponse()
  return proto.couriers.v1.DeleteResponse.deserializeBinaryFromReader(
    msg,
    reader
  )
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.couriers.v1.DeleteResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.couriers.v1.DeleteResponse}
 */
proto.couriers.v1.DeleteResponse.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {boolean} */ (reader.readBool())
        msg.setOk(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.couriers.v1.DeleteResponse.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.couriers.v1.DeleteResponse.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.couriers.v1.DeleteResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.couriers.v1.DeleteResponse.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getOk()
  if (f) {
    writer.writeBool(1, f)
  }
}

/**
 * optional bool ok = 1;
 * @return {boolean}
 */
proto.couriers.v1.DeleteResponse.prototype.getOk = function () {
  return /** @type {boolean} */ (
    jspb.Message.getBooleanFieldWithDefault(this, 1, false)
  )
}

/**
 * @param {boolean} value
 * @return {!proto.couriers.v1.DeleteResponse} returns this
 */
proto.couriers.v1.DeleteResponse.prototype.setOk = function (value) {
  return jspb.Message.setProto3BooleanField(this, 1, value)
}

goog.object.extend(exports, proto.couriers.v1)
